### PR TITLE
feat: add --exact option for generating install commands

### PR DESCRIPTION
**Pull request by gligoran**

### CODE REVIEW

**Comment by danvk** [comment]
Hi, thanks! I haven't used `-E` myself before. Does it make sense to use it without a version number?

**Comment by gligoran** [comment]
@danvk Yes. It saves the latest current version, but doesn't add any prefix characters like `~` or `^`. We use this all the time at my company.

**Comment by danvk** [comment]
What's the advantage of doing it this way instead of relying on `package-lock.json` or `yarn.lock` to pin your versions? I did some searching but couldn't find any articles recommending `--save-exact` that were less than 3–4 years old. Putting precise versions in `package.json` has some downsides, too: you're much more likely to get multiple versions of the same package nested in your node_modules.

**Comment by gligoran** [comment]
Sorry for the late reply. It's not that there's any advantage, but some projects in our company have all their dependencies set to exact versions.

This PR doesn't enforce the exact versions it just add the option for the user if they want it.

**Pull request closed without merging**
